import { getRandomInt } from './random';

const GAMES = [
  '50 Cent: Bulletproof',
  "Assassin's Creed",
  'Battlefield III',
  'Battlefield IV',
  'BlazBlue II: Continuum Shift',
  'Blitz I: The League',
  'Blood',
  'BMX XXX',
  'Bully',
  'Call of Duty IV: Modern Warfare',
  'Call of Duty: Black Ops II',
  'Carmageddon',
  'Carmageddon II: Carpocalypse Now',
  'Catherine',
  'Command & Conquer Generals',
  'Commandos I: Behind Enemy Lines',
  'Condemned I: Criminal Origins',
  'Condemned II: Bloodshot',
  'Counter-Strike',
  "Dante's Inferno",
  'Dark Sector',
  'Darksiders',
  'Dead Island',
  'Dead Island: Riptide',
  'Dead Rising',
  'Dead Rising II',
  'Doom',
  'Dragon Age II',
  'Dragon Age: Origins',
  'Dreamweb',
  'Duke Nukem 3D',
  'EA Sports MMA',
  'EverQuest',
  'Fallout IV: New Vegas',
  'Football Manager 2005',
  'God of War (series)',
  'Grand Theft Auto (series)',
  'Grand Theft Auto III',
  'Grand Theft Auto V',
  'Grand Theft Auto: Episodes from Liberty City',
  'Grand Theft Auto: Vice City',
  'Half-Life',
  'Harvester',
  'Hearts of Iron',
  'Heavy Rain',
  'Heavy Rain',
  'Homefront',
  'Hotline Miami II: Wrong Number',
  'I.G.I.-2: Covert Strike',
  'Injustice: Gods Among Us',
  'Kira Hara',
  'KZ Manager',
  'L.A. Noire',
  'Left 4 Dead II',
  'Leisure Suit Larry:Magna Cum Laude',
  'Mafia II',
  'Manhunt (series)',
  'Manhunt II',
  "Marc Eckō's Getting Up:Contents Under Pressure",
  'Mass Effect',
  'Mass Effect II',
  'Mass Effect III',
  'Max Payne',
  'Medal of Honor IVX: Warfighter',
  'Mercenaries I: Playground of Destruction',
  'Mortal Kombat',
  'Mortal Kombat II',
  'Mortal Kombat III',
  'Mortyr',
  'NARC (2005)',
  'NecroVisioN',
  'Phantasmagoria',
  'Pokémon Trading Card Game',
  'Postal',
  'Postal II',
  'Postal II Demo Game',
  'Red Dead Redemption',
  'Requiem: Avenging Angel',
  'Reservoir Dogs',
  'Risen',
  'Saints Row III',
  'Saints Row IV',
  'Saints Row IV',
  'Scarface: The World is Yours',
  'Shellshock II: Blood Trails',
  'Silent Hill VI: Homecoming',
  'Soldier of Fortune III: Payback',
  'Sonic Blast Man',
  'South Park: The Stick of Truth',
  'Spec Ops XI: The Line',
  'State of Decay',
  'Syndicate',
  'The Cat In The Hat',
  'The Darkness',
  'The Getaway',
  'The Godfather II',
  'The Guy Game',
];

class Fakes {
  getListOfGames(length = 10) {
    const splitPoint = getRandomInt(GAMES.length - length);

    return GAMES.splice(splitPoint, length);
  }
}

export const FakesUtil = new Fakes();
